
/*
   Generated file. Do not edit this file manually. Launch `gulp fup:manifest` in order to generate this again.
 */

(function() {
  if (this.ledger == null) {
    this.ledger = {};
  }

  ledger.build = {};

  ledger.build.Mode = 'release';

  ledger.build.Network = 'bitcoin';

  ledger.build.Flavors = ["bitcoin", "release", "all"];

  ledger.build.Time = 1510961234857;

  ledger.build.Commit = 'ea230cade0539fb502d13461b3cbb257de5ce07c';

  ledger.build.Version = '1.9.10';

}).call(this);
