
/*
   Generated file. Do not edit this file manually. Launch `gulp fup:manifest` in order to generate this again.
 */

(function() {
  if (this.ledger == null) {
    this.ledger = {};
  }

  ledger.build = {};

  ledger.build.Mode = 'release';

  ledger.build.Network = 'bitcoin';

  ledger.build.Flavors = ["bitcoin", "release", "all"];

  ledger.build.Time = 1510161870074;

  ledger.build.Commit = 'fa6e159d5be26854df786cff65ca80785e2737b9';

  ledger.build.Version = '1.9.7';

}).call(this);
